[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[build]	
    command = "yarn build"
    build = "build"

[build.environment]	
    NODE_ENV = "development"	

[context.production.environment]	
    NODE_ENV = "production"